version: "3"

services: 
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: server
      MYSQL_PASSWORD: server
  nuxt:
    build: nuxt
    volumes:
      - ./nuxt:/app
  server: 
    build: server
    volumes: 
      - ./server:/go/src/github.com/ShikinamiAsuka/ih13/server
    links: 
      - db
    environment:
      DB_HOST: db:3306
      DB_PASS: server
  proxy:
    image: nginx
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    ports:
      -  80:80
    links:
      - server
      - nuxt
