version: '3'

services: 
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: server
      MYSQL_PASSWORD: server
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  nuxt:
    build: nuxt
    volumes:
      - ./nuxt:/app
  api: 
    build: api
    volumes: 
      - ./api:/go/src/github.com/19700101000000/system-sample/api
    links: 
      - db
    environment:
      DB_HOST: db:3306
      DB_NAME: system_sample
      DB_USER: server
      DB_PASS: server
  proxy:
    image: nginx
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    ports:
      -  80:80
    links:
      - api
      - nuxt
