version: '3'

services: 
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: server
      MYSQL_PASSWORD: server
  vue:
    build: vue
    volumes:
      - ./vue:/app
  server: 
    build: server
    volumes: 
      - ./server:/go/src/github.com/19700101000000/system-sample/server
    links: 
      - db
    environment:
      DB_HOST: db:3306
      DB_PASS: server
  proxy:
    image: nginx
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    ports:
      -  80:80
    links:
      - server
      - vue
